// Loader + types for the static world-marker dataset rendered by /atlas.
//
// Generated by scripts/fetch-map-markers.mjs from the community
// Satisfactory-Calculator Interactive Map data. Coordinates are UE world units
// (1 unit = 1 cm) — the same space lib/save/parse.ts reports actor
// translations in, so atlas markers line up with a save's factory footprint.

import { assetPath } from '@/lib/utils/paths';

export type MarkerCategory = 'nodes' | 'wells' | 'slugs' | 'artifacts' | 'collectibles';

export type MarkerPurity = 'impure' | 'normal' | 'pure';

export interface WorldMarker {
  x: number;
  y: number;
  z: number;
  /** Node/well purity. Absent for slugs, artifacts, and drop pods. */
  purity?: MarkerPurity;
  /** Distinguishes variants inside one layer: slug color (`green`/`yellow`/
   *  `purple`) or artifact kind (`mercer`/`somersloop`). */
  subtype?: string;
}

export interface MarkerLayer {
  /** Stable toggle key, e.g. `nodes.iron-ore`. */
  id: string;
  label: string;
  category: MarkerCategory;
  /** Desc_*_C class of the extracted resource, when the layer maps to one.
   *  Not every class exists in SatData.items (e.g. Desc_Geyser_C). */
  item?: string;
  count: number;
  markers: WorldMarker[];
}

export interface MapMarkers {
  attribution: string;
  sourceUrl: string;
  sourceVersion: string;
  generatedAt: string;
  layers: MarkerLayer[];
}

let cache: Promise<MapMarkers> | null = null;

/** Loads /data/map-markers.json, cache-busted by the dataset buildId the same
 *  way loadGameData() busts satisfactory.json. Both files are regenerated
 *  together by `npm run refresh`. */
export function loadMapMarkers(): Promise<MapMarkers> {
  if (cache) return cache;
  cache = (async () => {
    let buildId = 'unknown';
    try {
      const v = await fetch(assetPath('/data/version.json'), { cache: 'no-store' });
      if (v.ok) {
        const j = (await v.json()) as { buildId?: string };
        if (j.buildId) buildId = j.buildId;
      }
    } catch {
      /* fall through — a static URL still works, it just won't bust the cache */
    }
    const url = `${assetPath('/data/map-markers.json')}?v=${encodeURIComponent(buildId)}`;
    const r = await fetch(url, { cache: 'force-cache' });
    if (!r.ok) throw new Error(`Failed to load map markers: ${r.status}`);
    return (await r.json()) as MapMarkers;
  })();
  return cache;
}

export function clearMarkerCache() {
  cache = null;
}
